---

version: '3'

services:
  jenkinsci:
    image: jenkinsci/blueocean
    container_name: jenkinsci
    restart: always
    environment:
      - VIRTUAL_HOST=${HOSTNAME}
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=${HOSTNAME}
      - LETSENCRYPT_EMAIL=${ADMIN_EMAIL}
    #ports:
    #  - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./backups/:/backups

networks:
    default:
        external:
            name: webproxy